[package]
name = "jsdotlua/virtualized-list"
version = "1.3.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Flipper = "reselim/flipper@2.0.0"
Promise = 'evaera/promise@4.0.0'
React = 'core-packages/react@17.0.1-rc.19'
